### ISSUE TITLE
Could you explain cleanSessionData()?

### ISSUE THREAD

**Issue by bartt** [davglass/express-session-mongo#2]
Dav,

could you explain the cleanSessionData() function? You're copying over all object attributes but you're also converting some attributes to a number. What the purpose of that?

**Comment by davglass** [comment]
It's a way to convert a MongoDB document into the original Javascript. When Mongo Stores the number (as a document), it stores it in a special way to allow it to be queried. I'm simply converting it back into a JS Number format.

I will likely need to add more checks here to clean up Mongo Data from the original.

**Comment by bartt** [comment]
I see. I found that the conversion to number wasn't working properly in native mode. I had to resort to BSONPure for a correct conversion.
